/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CustomerControl;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import model.Customer;

/**
 *
 * @author DELL
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
         this.setLocationRelativeTo(null);
        ButtonGroup group = new ButtonGroup();
        group.add(addCustomerGenderMale);
        group.add(addCustomerGenderFemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        addCustomerlabel = new javax.swing.JLabel();
        addCustomerbuttonHome = new javax.swing.JButton();
        addCustomerbuttonCustomers = new javax.swing.JButton();
        addCustomerlabelCustomerName = new javax.swing.JLabel();
        addCustomerlabelEmail = new javax.swing.JLabel();
        addCustomerNameText = new javax.swing.JTextField();
        addCustomerEmailText = new javax.swing.JTextField();
        addCustomerlabelEmail1 = new javax.swing.JLabel();
        addCustomerAddressText = new javax.swing.JTextField();
        addCustomerlabelEmail2 = new javax.swing.JLabel();
        addCustomerContactNumberText = new javax.swing.JTextField();
        addCustomerlabelGender = new javax.swing.JLabel();
        addCustomerDateOfBirthText = new org.jdesktop.swingx.JXDatePicker();
        addCustomerlabelEmail4 = new javax.swing.JLabel();
        addCustomerGenderFemale = new javax.swing.JRadioButton();
        addCustomerGenderMale = new javax.swing.JRadioButton();
        addCustomerButton = new javax.swing.JButton();
        addCustomerClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Customer");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setToolTipText("Add Customer");
        jPanel1.setName("Add Customer"); // NOI18N

        addCustomerlabel.setFont(new java.awt.Font("Yu Mincho Demibold", 0, 18)); // NOI18N
        addCustomerlabel.setForeground(new java.awt.Color(255, 255, 0));
        addCustomerlabel.setText("Add Customer");

        addCustomerbuttonHome.setBackground(new java.awt.Color(204, 204, 255));
        addCustomerbuttonHome.setText("Home");
        addCustomerbuttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerbuttonHomeActionPerformed(evt);
            }
        });

        addCustomerbuttonCustomers.setBackground(new java.awt.Color(204, 204, 255));
        addCustomerbuttonCustomers.setText("Customers");
        addCustomerbuttonCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerbuttonCustomersActionPerformed(evt);
            }
        });

        addCustomerlabelCustomerName.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        addCustomerlabelCustomerName.setForeground(new java.awt.Color(255, 255, 0));
        addCustomerlabelCustomerName.setText("Customer Name");

        addCustomerlabelEmail.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        addCustomerlabelEmail.setForeground(new java.awt.Color(255, 255, 0));
        addCustomerlabelEmail.setText("Address");

        addCustomerlabelEmail1.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        addCustomerlabelEmail1.setForeground(new java.awt.Color(255, 255, 0));
        addCustomerlabelEmail1.setText("Email");

        addCustomerlabelEmail2.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        addCustomerlabelEmail2.setForeground(new java.awt.Color(255, 255, 0));
        addCustomerlabelEmail2.setText("Date of Birth");

        addCustomerlabelGender.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        addCustomerlabelGender.setForeground(new java.awt.Color(255, 255, 0));
        addCustomerlabelGender.setText("Gender");

        addCustomerlabelEmail4.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        addCustomerlabelEmail4.setForeground(new java.awt.Color(255, 255, 0));
        addCustomerlabelEmail4.setText("Contact Number");

        addCustomerGenderFemale.setForeground(new java.awt.Color(204, 204, 0));
        addCustomerGenderFemale.setText("Female");

        addCustomerGenderMale.setForeground(new java.awt.Color(204, 204, 0));
        addCustomerGenderMale.setText("Male");

        addCustomerButton.setText("Add Customer");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        addCustomerClearButton.setText("Clear");
        addCustomerClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addCustomerlabelEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerlabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerlabelCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerlabelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerlabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerlabelEmail4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(addCustomerbuttonCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(addCustomerbuttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addCustomerGenderMale)
                            .addComponent(addCustomerEmailText)
                            .addComponent(addCustomerNameText)
                            .addComponent(addCustomerAddressText)
                            .addComponent(addCustomerContactNumberText)
                            .addComponent(addCustomerDateOfBirthText, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(addCustomerGenderFemale)
                            .addComponent(addCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(addCustomerClearButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addCustomerEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addCustomerlabelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCustomerlabel)
                            .addComponent(addCustomerbuttonCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCustomerbuttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCustomerlabelCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCustomerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerlabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerContactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerlabelEmail4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerDateOfBirthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerlabelEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerlabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerGenderMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCustomerGenderFemale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerButton)
                    .addComponent(addCustomerClearButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        Customer addCustomer = new Customer();
        addCustomer.setCustomerName(addCustomerNameText.getText());
        addCustomer.setCustomerEmail(addCustomerEmailText.getText());
        addCustomer.setAddress(addCustomerAddressText.getText());
        addCustomer.setContactNumber(addCustomerContactNumberText.getText());
        Date date = addCustomerDateOfBirthText.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date1 = dateFormat.format(date);
        addCustomer.setDateOfBirth(date1);
        String gender = "";
        if (addCustomerGenderMale.isSelected()) {
            gender = "male";
        } else if (addCustomerGenderFemale.isSelected()) {
            gender = "female";
        }
        addCustomer.setGender(gender);

        CustomerControl.addCustomer(addCustomer);
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void addCustomerbuttonCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerbuttonCustomersActionPerformed
        new Customers().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_addCustomerbuttonCustomersActionPerformed

    private void addCustomerbuttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerbuttonHomeActionPerformed
        new Home().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_addCustomerbuttonHomeActionPerformed

    private void addCustomerClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerClearButtonActionPerformed
        addCustomerNameText.setText("");
        addCustomerEmailText.setText("");
        addCustomerAddressText.setText("");
        addCustomerContactNumberText.setText("");
    }//GEN-LAST:event_addCustomerClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addCustomerAddressText;
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addCustomerClearButton;
    private javax.swing.JTextField addCustomerContactNumberText;
    private org.jdesktop.swingx.JXDatePicker addCustomerDateOfBirthText;
    private javax.swing.JTextField addCustomerEmailText;
    private javax.swing.JRadioButton addCustomerGenderFemale;
    private javax.swing.JRadioButton addCustomerGenderMale;
    private javax.swing.JTextField addCustomerNameText;
    private javax.swing.JButton addCustomerbuttonCustomers;
    private javax.swing.JButton addCustomerbuttonHome;
    private javax.swing.JLabel addCustomerlabel;
    private javax.swing.JLabel addCustomerlabelCustomerName;
    private javax.swing.JLabel addCustomerlabelEmail;
    private javax.swing.JLabel addCustomerlabelEmail1;
    private javax.swing.JLabel addCustomerlabelEmail2;
    private javax.swing.JLabel addCustomerlabelEmail4;
    private javax.swing.JLabel addCustomerlabelGender;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
