/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProductControl;
import java.math.BigDecimal;
import model.Product;

/**
 *
 * @author DELL
 */
public class EditProduct extends javax.swing.JFrame {

    /**
     * Creates new form EditProduct
     */
    public EditProduct() {
        initComponents();
        
         this.setLocationRelativeTo(null);
    }
     public EditProduct(Product p) {
        initComponents();
        editproductNameId.setText(Integer.toString (p.getProductId()));
        editproductNameText.setText(p.getProductName());
        editdescriptionText.setText(p.getDescripion());
        editpurchasePriceText.setText(p.getPurchasePrice().toString());
        editsellingPiceText.setText(p.getSellingPrice().toString());
       editquantityText.setText(Integer.toString(p.getQuantity()));
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        editProductlabel = new javax.swing.JLabel();
        editProductbuttonHome = new javax.swing.JButton();
        editProductbuttonProducts = new javax.swing.JButton();
        editProductlabelDescription = new javax.swing.JLabel();
        editProductlabelProductName = new javax.swing.JLabel();
        editProductlabelQuantity = new javax.swing.JLabel();
        editProductlabelPurchasePrice = new javax.swing.JLabel();
        editProductlabelSellingPrice = new javax.swing.JLabel();
        editproductNameText = new javax.swing.JTextField();
        editdescriptionText = new javax.swing.JTextField();
        editpurchasePriceText = new javax.swing.JTextField();
        editsellingPiceText = new javax.swing.JTextField();
        editquantityText = new javax.swing.JTextField();
        editProductButton = new javax.swing.JButton();
        editProductlabelProductId = new javax.swing.JLabel();
        editproductNameId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Product");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        editProductlabel.setFont(new java.awt.Font("Yu Mincho Demibold", 0, 18)); // NOI18N
        editProductlabel.setForeground(new java.awt.Color(255, 255, 0));
        editProductlabel.setText("Edit Products");

        editProductbuttonHome.setBackground(new java.awt.Color(204, 204, 255));
        editProductbuttonHome.setText("Home");
        editProductbuttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductbuttonHomeActionPerformed(evt);
            }
        });

        editProductbuttonProducts.setBackground(new java.awt.Color(204, 204, 255));
        editProductbuttonProducts.setText("Products");
        editProductbuttonProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductbuttonProductsActionPerformed(evt);
            }
        });

        editProductlabelDescription.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        editProductlabelDescription.setForeground(new java.awt.Color(255, 255, 0));
        editProductlabelDescription.setText("Description");

        editProductlabelProductName.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        editProductlabelProductName.setForeground(new java.awt.Color(255, 255, 0));
        editProductlabelProductName.setText("Product Name");

        editProductlabelQuantity.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        editProductlabelQuantity.setForeground(new java.awt.Color(255, 255, 0));
        editProductlabelQuantity.setText("Quantity");

        editProductlabelPurchasePrice.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        editProductlabelPurchasePrice.setForeground(new java.awt.Color(255, 255, 0));
        editProductlabelPurchasePrice.setText("Purchase Price");

        editProductlabelSellingPrice.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        editProductlabelSellingPrice.setForeground(new java.awt.Color(255, 255, 0));
        editProductlabelSellingPrice.setText("Selling  Price");

        editProductButton.setBackground(new java.awt.Color(204, 204, 255));
        editProductButton.setText("Edit Product");
        editProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductButtonActionPerformed(evt);
            }
        });

        editProductlabelProductId.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        editProductlabelProductId.setForeground(new java.awt.Color(255, 255, 0));
        editProductlabelProductId.setText("Product ID");

        editproductNameId.setEditable(false);
        editproductNameId.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(editProductlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editProductlabelQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editProductlabelPurchasePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(editProductlabelSellingPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editProductlabelProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editProductlabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editproductNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(editpurchasePriceText)
                                .addComponent(editdescriptionText)
                                .addComponent(editsellingPiceText)
                                .addComponent(editquantityText)
                                .addComponent(editProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                            .addComponent(editproductNameId, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(editProductbuttonProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editProductbuttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(editProductlabelProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(535, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editProductlabel)
                    .addComponent(editProductbuttonProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editProductbuttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editProductlabelProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editproductNameId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(editproductNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editProductlabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editdescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editProductlabelPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editpurchasePriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editProductlabelSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editsellingPiceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editProductlabelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editquantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(editProductButton)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addComponent(editProductlabelProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(267, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductButtonActionPerformed
        Product addProduct2=new Product();
        addProduct2.setProductId(Integer.parseInt(editproductNameId.getText()));
        addProduct2.setProductName(editproductNameText.getText());
        addProduct2.setDescripion(editdescriptionText.getText());
        addProduct2.setPurchasePrice(new BigDecimal(editpurchasePriceText.getText()));
        addProduct2.setSellingPrice(new BigDecimal(editsellingPiceText.getText()));
        addProduct2.setQuantity(Integer.parseInt(editquantityText.getText()));
        
        ProductControl.editProduct(addProduct2);
      

    }//GEN-LAST:event_editProductButtonActionPerformed

    private void editProductbuttonProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductbuttonProductsActionPerformed
        new Products().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_editProductbuttonProductsActionPerformed

    private void editProductbuttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductbuttonHomeActionPerformed
        new Home().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_editProductbuttonHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editProductButton;
    private javax.swing.JButton editProductbuttonHome;
    private javax.swing.JButton editProductbuttonProducts;
    private javax.swing.JLabel editProductlabel;
    private javax.swing.JLabel editProductlabelDescription;
    private javax.swing.JLabel editProductlabelProductId;
    private javax.swing.JLabel editProductlabelProductName;
    private javax.swing.JLabel editProductlabelPurchasePrice;
    private javax.swing.JLabel editProductlabelQuantity;
    private javax.swing.JLabel editProductlabelSellingPrice;
    private javax.swing.JTextField editdescriptionText;
    private javax.swing.JTextField editproductNameId;
    private javax.swing.JTextField editproductNameText;
    private javax.swing.JTextField editpurchasePriceText;
    private javax.swing.JTextField editquantityText;
    javax.swing.JTextField editsellingPiceText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
