/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProductControl;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Product;

/**
 *
 * @author DELL
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
        this.setLocationRelativeTo(null);
        displayProducts(ProductControl.getAllProducts());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productbuttonHome = new javax.swing.JButton();
        productsSearchText = new javax.swing.JTextField();
        productsSearchButton = new javax.swing.JButton();
        addProductLinkButton = new javax.swing.JButton();
        editProductLinkButton = new javax.swing.JButton();
        deleteProductButton = new javax.swing.JButton();
        productsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Products");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        productbuttonHome.setBackground(new java.awt.Color(204, 204, 255));
        productbuttonHome.setText("Home");
        productbuttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productbuttonHomeActionPerformed(evt);
            }
        });

        productsSearchButton.setText("Search");
        productsSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsSearchButtonActionPerformed(evt);
            }
        });

        addProductLinkButton.setText("Add Product");
        addProductLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductLinkButtonActionPerformed(evt);
            }
        });

        editProductLinkButton.setText("Edit Product");
        editProductLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductLinkButtonActionPerformed(evt);
            }
        });

        deleteProductButton.setText("Delete Product");
        deleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductButtonActionPerformed(evt);
            }
        });

        productsLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        productsLabel.setForeground(new java.awt.Color(204, 204, 0));
        productsLabel.setText("Products");

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Description", "Quantity", "Purchase Price", "Selling Price"
            }
        ));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(productsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(productsSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(productsSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(productbuttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(addProductLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(61, 61, 61)
                                    .addComponent(editProductLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(deleteProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(productsLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productsSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productsSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productbuttonHome))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteProductButton)
                    .addComponent(editProductLinkButton)
                    .addComponent(addProductLinkButton))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productsSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsSearchButtonActionPerformed
        if (productsSearchText.getText().equals("")) {
            new Products().setVisible(true);
            this.dispose();
        } else {
            List<Product> searchProducts = ProductControl.getSearchProducts(productsSearchText.getText());
            displayProducts(searchProducts);
        }
    }//GEN-LAST:event_productsSearchButtonActionPerformed

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked

    }//GEN-LAST:event_productTableMouseClicked

    private void editProductLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductLinkButtonActionPerformed
        int index = productTable.getSelectedRow();
        TableModel model = productTable.getModel();

        Product product = new Product();
        product.setProductId(Integer.parseInt(model.getValueAt(index, 0).toString()));
        product.setProductName(model.getValueAt(index, 1).toString());
        product.setDescripion(model.getValueAt(index, 2).toString());
        product.setQuantity(Integer.parseInt(model.getValueAt(index, 3).toString()));
        product.setPurchasePrice(new BigDecimal(model.getValueAt(index, 4).toString()));
        product.setSellingPrice(new BigDecimal(model.getValueAt(index, 5).toString()));

        EditProduct productEdit = new EditProduct(product);
        productEdit.setVisible(true);
        productEdit.pack();
        productEdit.setLocationRelativeTo(null);


    }//GEN-LAST:event_editProductLinkButtonActionPerformed

    private void productbuttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productbuttonHomeActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productbuttonHomeActionPerformed

    private void addProductLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductLinkButtonActionPerformed
        new AddProduct().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addProductLinkButtonActionPerformed

    private void deleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductButtonActionPerformed
        int index = productTable.getSelectedRow();
        TableModel model = productTable.getModel();
        Product product = new Product();
        product.setProductId(Integer.parseInt(model.getValueAt(index, 0).toString()));
        ProductControl.deleteProduct(product);
    }//GEN-LAST:event_deleteProductButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductLinkButton;
    private javax.swing.JButton deleteProductButton;
    private javax.swing.JButton editProductLinkButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    private javax.swing.JButton productbuttonHome;
    private javax.swing.JLabel productsLabel;
    private javax.swing.JButton productsSearchButton;
    private javax.swing.JTextField productsSearchText;
    // End of variables declaration//GEN-END:variables

    void displayProducts(List<Product> products) {
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        for (int i = 0; i < products.size(); i++) {
            row[0] = products.get(i).getProductId();
            row[1] = products.get(i).getProductName();
            row[2] = products.get(i).getDescripion();
            row[3] = products.get(i).getQuantity();
            row[4] = products.get(i).getPurchasePrice();
            row[5] = products.get(i).getSellingPrice();

            model.addRow(row);

        }
        productTable.setModel(model);
    }
}
